version: '2'

services:
  redis:
    image: redis:4
    container_name: redis
    restart: unless-stopped
    ports:
      - '6379:6379'

  postgres:
    image: postgres:10
    container_name: postgres
    restart: unless-stopped
    volumes:
      - ./docker/data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=demo
      - POSTGRES_USER=demo
      - POSTGRES_PASSWORD=demo
    ports:
      - '5432:5432'

  node:
    image: node:9-slim
    container_name: node
    restart: unless-stopped
    command: npm start
    working_dir: /code
    volumes:
      - ./:/code
    ports:
      - '3000:3000'
    depends_on:
      - redis
      - postgres

  nginx:
    image: nginx:1.13
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./public:/usr/share/nginx/html
    ports:
      - '80:80'
    depends_on:
      - node
