version: '2'

services:
  redis:
    image: arm32v6/redis:4.0-alpine
    restart: unless-stopped
    ports:
      - '6379:6379'

  postgres:
    image: arm32v6/postgres:10.4-alpine
    restart: unless-stopped
    volumes:
      - ./docker/data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=demo
      - POSTGRES_USER=demo
      - POSTGRES_PASSWORD=demo
    ports:
      - '5432:5432'

  node:
    image: arm32v6/node:9.6-alpine
    restart: unless-stopped
    command: npm start
    working_dir: /code
    volumes:
      - ./:/code
    depends_on:
      - redis
      - postgres

  nginx:
    image: arm32v6/nginx:1.15-alpine
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=tracker.wouterdeschuyter.be
      - LETSENCRYPT_HOST=tracker.wouterdeschuyter.be
      - LETSENCRYPT_EMAIL=wouter.de.schuyter@gmail.com
    volumes:
      - ./public:/usr/share/nginx/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - default
      - webproxy

networks:
  webproxy:
    external: true
