version: '3'

services:
  redis:
    image: redis:4
    container_name: redis
    restart: unless-stopped
    ports:
      - '6379:6379'

  node:
    image: node:9-slim
    container_name: node
    restart: unless-stopped
    command: node .
    working_dir: /code/server
    volumes:
      - ./:/code
    ports:
      - '3000:3000'
    depends_on:
      - redis
