version: 2
jobs:
  build:
    machine: true
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - dependencies-{{ checksum "package.json" }}
      - run:
          name: Dependencies
          command: make node_modules
      - save_cache:
          paths:
          - ./node_modules
          key: dependencies-{{ checksum "package.json" }}
      - run:
          name: Linting
          command: make lint
