# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    machine: true
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Dependencies
          command: make dependencies
      - run:
          name: Linting
          command: make lint
      - run:
          name: Build
          command: make build
      - run:
          name: Push docker image
          command: |
            docker login docker.wouterdeschuyter.be -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
            make push
            make push-latest
