version: 2
jobs:
  build:
    machine: true
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Dependencies
          command: make dependencies
      - run:
          name: Linting
          command: make lint
