version: '2'

services:
  mariadb:
    image: mariadb:10.4
    volumes:
      - ./data/mariadb:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root

  node:
    image: node:12-slim
    command: ["npm", "run", "start:dev"]
    volumes:
      - ./../:/code
    environment:
      - PORT=3001
    working_dir: /code
    restart: unless-stopped
    ports:
      - "3001:3001"
