version: '2'

services:
  nginx:
    image: docker.wouterdeschuyter.be/env-tracker-nginx
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=tracker.wouterdeschuyter.be
      - LETSENCRYPT_HOST=tracker.wouterdeschuyter.be
      - LETSENCRYPT_EMAIL=wouter.de.schuyter@gmail.com
    networks:
      - default
      - webproxy
    logging:
      options:
        max-size: 2m
        max-file: '5'

networks:
  webproxy:
    external: true
